export interface Product {
    index: number
    businessReason: string
    productName: string
    publisher: string
    version: string
    edition: string
    releaseDate: string
    standard: boolean
    costs: number
    price: number
    timeperiod: string
    logo: string
    requirements: string
    location: string
    linkToWebsite: string
    externalID: number
    prereqireties: string
    functionality: string
    departement: string
    role: string
    category: string
    tags: string[]
    name: string
    descripton: string
    technicalOwner: string
    businessOwner: string
    contractOwner: string
    OLA: string
    appClassification: string
    lifecycleState: string
    SWOApproved: string
    approvalType: string
    internalID: number
    licenseModel: string
    licenseLevel: string
}