import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { GraphProfil } from './models/profile';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class RequestService {

  constructor(private http: HttpClient) { }

  Get(): Observable<GraphProfil>{
    const url = "https://graph.microsoft.com/v1.0/me";
    const token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6ImVSZDUwb0ltSHB5TU94SnRYTVdXTXp0NjdTNVNlT3VXTWY1bnFVenJUT1kiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8xZGM5YjMzOS1mYWRiLTQzMmUtODZkZi00MjNjMzhhMGZjYjgvIiwiaWF0IjoxNjgzMTA0NzkwLCJuYmYiOjE2ODMxMDQ3OTAsImV4cCI6MTY4MzEwOTU0NCwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXI6cmVnaXN0ZXJzZWN1cml0eWluZm8iXSwiYWlvIjoiQVRRQXkvOFRBQUFBamZEd3BCYisyUjdabnRVTWZ4cEU3QkU5UGthQXA4elErZTBtMnFpZ3VqYkJwZk5lQkJRMEdNVWFyQ1hqWm0vayIsImFtciI6WyJwd2QiLCJyc2EiXSwiYXBwX2Rpc3BsYXluYW1lIjoiR3JhcGggRXhwbG9yZXIiLCJhcHBpZCI6ImRlOGJjOGI1LWQ5ZjktNDhiMS1hOGFkLWI3NDhkYTcyNTA2NCIsImFwcGlkYWNyIjoiMCIsImRldmljZWlkIjoiZjA3NzYwMWQtZmViNi00YjkzLWIyZmQtMWY5NjVmOTg3YjUxIiwiZmFtaWx5X25hbWUiOiJMdWR3aWciLCJnaXZlbl9uYW1lIjoiTWljaGFlbCIsImlkdHlwIjoidXNlciIsImlwYWRkciI6Ijg1LjIzMi4xOC4yNyIsIm5hbWUiOiJMdWR3aWcsIE1pY2hhZWwiLCJvaWQiOiJlOWE5ZGRjYS1lZjhkLTRhNDMtOTJmOC1mYjczYjA2YmE4OTYiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMTY1ODY4NDQwNy0zMzMwNDc1NDcxLTM4OTY2MDM0NzEtNjE0NzQyIiwicGxhdGYiOiIzIiwicHVpZCI6IjEwMDMyMDAyMUVFQkQ4ODgiLCJyaCI6IjAuQVZ3QU9iUEpIZHY2TGtPRzMwSThPS0Q4dUFNQUFBQUFBQUFBd0FBQUFBQUFBQUJjQU5zLiIsInNjcCI6IkRpcmVjdG9yeS5SZWFkLkFsbCBvcGVuaWQgcHJvZmlsZSBVc2VyLlJlYWQgZW1haWwiLCJzaWduaW5fc3RhdGUiOlsiZHZjX21uZ2QiLCJkdmNfY21wIiwiaW5rbm93bm50d2siLCJrbXNpIl0sInN1YiI6ImdkckNZYUhCS1ByMlBFZ2xLSmVwU0U0a0M5MXVnemJQOWd1aXgxc0lTS28iLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiRVUiLCJ0aWQiOiIxZGM5YjMzOS1mYWRiLTQzMmUtODZkZi00MjNjMzhhMGZjYjgiLCJ1bmlxdWVfbmFtZSI6Im1pY2hhZWwubHVkd2lnQHNvZnR3YXJlb25lLmNvbSIsInVwbiI6Im1pY2hhZWwubHVkd2lnQHNvZnR3YXJlb25lLmNvbSIsInV0aSI6Ino5M1ZkdjE2UkVPRm1EU0dDNmRRQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfY2MiOlsiQ1AxIl0sInhtc19zdCI6eyJzdWIiOiJqN2FrOGk4WWd6SWpnRFBsOGJFNGo4dThySHFicFJLWEZVMkVxSVBwUEZNIn0sInhtc190Y2R0IjoxNDM5OTY5NDE1LCJ4bXNfdGRiciI6IkVVIn0.ErtdG7Kt-YR3JuPeR8ia9pTddCwLA5BlxXJjoG8yhqPuD74_rf0oZ3Fp7gQom7R2lh7p8K88SbHnyW9FSGHKFEvASiP939itISR4DVcpo3XueIeTHwbajBVcffHqMFIXHE3DQQfrWvsSwHD-sbvxTftZYr88gCrXt99GV23dV0kw_NTgSgdmsASQ7Gk54nZcNHvZggoHppYvjoRPQTCixh4oi2_uWn_5ZdBWY8PeLwYTBm-2yKlvkxuVmMANNIbcEG3xv4h_jvMf7R2CyG2pXAH_ojsgmy0_Q0bZhSxj2js8KubvNQmJUKB13wFzkFlCLtR2ian-JIjLGHFOtdU-TA"
    let data = this.http.get<GraphProfil>(url, { headers: new HttpHeaders({ 'Authorization': `Bearer ${token}` }), responseType: "json" });
    return data
  }
  
}
